name: 'Sloop Launch'
description: 'Remove deployments from the deleted branch'
author: 'themath123'

# Define your inputs here.
inputs:
  token:
    description: 'Your Github token'
    required: true
  owner:
    description: 'Your Github name or organization'
    required: true
  repo:
    description: 'Your repository'
    required: true

# Define your outputs here.
outputs:
  result:
    description: 'If action ended successfully, return true or false'
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
